### ISSUE TITLE
add `remove` option

### ISSUE THREAD

**Issue by davidmarkclements** [davidmarkclements/fast-redact#1]
as suggested by @jasnell

**Comment by Strajk** [comment]
I believe you have already done it :)) https://github.com/davidmarkclements/fast-redact/commit/11ccb956c6f0fdc803941ef0a8390d8e4af235ec

thx for the repo, I've learned a lot reading source code :)

**Comment by davidmarkclements** [comment]
Haha that's right I can close now 

Thanks @strajk!
