### ISSUE TITLE
Should restore original object when the first call is precensored

### ISSUE THREAD

**Issue by adrianolek** [davidmarkclements/fast-redact#29]
When the first call has the redacted property value equal the `censor` value, then subsequent calls will not restore the redacted property in the original object.

I've created a test case, please have a look:

https://github.com/adrianolek/fast-redact/blob/first-call-precensored/test/index.js#L292

Started in https://github.com/pinojs/pino/issues/919

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.
