### ISSUE TITLE
Optional throw Error?

### ISSUE THREAD

**Issue by robmcguinness** [davidmarkclements/fast-redact#3]
I'm using a redacted path like `['data.username']`. **fast-redact** produces the following method signature for redaction:

```js
(function(o
/*``*/) {

    if (typeof o !== 'object' || o == null) {
      throw Error('fast-redact: primitives cannot be redacted')
    }
    const { censor, secret } = this
    
      if (o.username != null) {
        const val = o.username
        if (val === censor) {
          secret["username"].precensored = true
        } else {
          secret["username"].val = val
          o.username = censor
          
      switch (true) {
        
      }
    
        }
      }
...

})
```

When using a library like [axios](https://github.com/axios/axios), `data` can be either an object or a string when content type is `application/json` vs `application/x-www-form-urlencoded`. What are some thoughts about having a setting to just ignore redaction if an `o` is primitive vs throwing an error?

**Comment by robmcguinness** [comment]
FYI I'm using **pino** `v5` with redact settings.

**Comment by mcollina** [comment]
I don’t really understand what is the problem.

**Comment by robmcguinness** [comment]
absolutely. i'll setup an example.

**Comment by robmcguinness** [comment]
Please check out the example when you can: https://github.com/robmcguinness/pino/commit/85b410fb74e521549811549dcb37c0f207205d3e. Example inlined for reference.
```js
test('redact – optional throw for primitives', async ({ is }) => {
  const stream = sink()
  const instance = pino({ redact: ['data.username'] }, stream)
  instance.info({
    data: {
      username: 'a'
    }
  })
  let { data } = await once(stream, 'data')
  is(data.username, '[Redacted]')

  // Don't throw just ignore?
  instance.info({
    data: 'b'
  })

  // Value should just pass through
  data = await once(stream, 'data')
  is(data, 'b')
})
```

**Comment by mcollina** [comment]
I think ignoring is the correct behavior. One of the key principles in pino is that _logging a line should never throw_ (like `console.log`). 

In your case, we are looking for a `username` property on the `data` object. 
I would recommend using a library like [Joy](http://npm.im/joy) or [Ajv](http://npm.im/ajv) to validate and normalize your inputs so that it always have the same properties.

**Comment by davidmarkclements** [comment]
Yes it should be ignoring - the throw is a mistake. PR's very welcome

**Comment by robmcguinness** [comment]
Thanks for feedback. I'll submit a PR soon.
