### ISSUE TITLE
Wildcard key redaction breaks on strings

### ISSUE THREAD

**Issue by 72636c** [davidmarkclements/fast-redact#31]
`fast-redact` is used in [Pino](https://github.com/pinojs/pino) to support redaction of log fields.

For example, we may want to redact a path that may contain PII:

```typescript
const fastRedact = require('fast-redact');

const redact = fastRedact({ paths: ['pii.*'] });

const goodLog = { msg: 'this is fine', pii: { name: 'Jean Doe' } };

redact(goodLog);
// => { msg: 'this is fine', pii: { name: '[REDACTED]' } }
```

However, logs can be unstructured. What if the `pii` field is a string?

```typescript
const fastRedact = require('fast-redact');

const redact = fastRedact({ paths: ['pii.*'] });

const log = { msg: 'this is fine', pii: '😈' };

redact(log);
// => TypeError: Cannot assign to read only property '0' of string '😈'
```

I think the desired behaviour here would be for `fast-redact` to pass through the string untouched rather than throwing a runtime error.

**Comment by mcollina** [comment]
Thanks! Would you like to send a PR to fix this bug?
