### ISSUE TITLE
`createContext is not a function` error thrown in validator.js

### ISSUE THREAD

**Issue by rushi** [davidmarkclements/fast-redact#37]
Hi, I'm trying to use this package in a React app to redact sensitive tokens before logging the information to a remote server and have run into a problem. I'd like some help!

The error in the console is:
```
validator.js:34 Uncaught Error: fast-redact – Invalid path (headers.cookie)
    at validator.js:34
    at Array.forEach (<anonymous>)
    at validate (validator.js:14)
    at fastRedact (index.js:39)
```

However when I step into the code and look inside validator.js, the actual exception thrown is `createContext is not a function` 
![image](https://user-images.githubusercontent.com/65708/119435575-0420aa80-bd38-11eb-81d3-c6025067db90.png)

Right now I'm simply using the code provided in the Readme, but using an `import` instead of a `require`
```js
import fastRedact from "fast-redact";
const redact = fastRedact({
    paths: ["headers.cookie", "headers.referer"],
});
const fauxRequest = {
    headers: {
      host: 'http://example.com',
      cookie: `oh oh we don't want this exposed in logs in etc.`,
      referer: `if we're cool maybe we'll even redact this`
    }
  }
console.log("Redacted Payload", redact(fauxRequest));
```

**Comment by mcollina** [comment]
This module is designed to run inside Node and not in the browser... would you like to send a PR to add such support?

**Comment by jsumners** [comment]
In particular, `createContext` is a function exported by the `vm` module provided by Node core.

**Comment by rushi** [comment]
That's what I assumed, but had to ask. 

@mcollina Not interested in working on a PR at the moment.
