### ISSUE TITLE
can't redact parameters that contains - character

### ISSUE THREAD

**Issue by e-tip** [davidmarkclements/fast-redact#48]
Hi, I'm trying to use fast-redact to redact headers that comes from an api gateway request.
In this request there's an header containing the customer api key called x-api-key.
This code throws an exception in the validator 
```
const params = req.headers
const redact = fastRedact({
        paths: ['x-api-key'],
        serialize: false
    });
    const redacted = redact(params);
```
Throws this exception 
```
ReferenceError: api is not defined
  at evalmachine.<anonymous>:4:17
    at evalmachine.<anonymous>:6:13
    at Script.runInContext (node:vm:139:12)
    at runInContext (node:vm:289:6)
    at /Users/tiziano_faion/BizAway/RiskAssessment/node_modules/bizlogger/node_modules/fast-redact/lib/validator.js:24:9
```

**Comment by jsumners** [comment]
This test indicates that `x-api-key` should be redactable:

https://github.com/davidmarkclements/fast-redact/blob/92b27f280aa28ecc01b3a844bdf0c5c67d25a7c3/test/index.js#L231-L232

Please provide a minimal reproduction.

**Comment by e-tip** [comment]
You can find a zip attached 

[Archivio.zip](https://github.com/davidmarkclements/fast-redact/files/8989519/Archivio.zip)

**Comment by e-tip** [comment]
Looking better in the code, i managed to make it work passing the x-api-key in this way
paths: ["['x-api-key']"],

**Comment by aellerton** [comment]
For anyone facing similar problems with a name including a hyphen (`-`) char, I've provided two examples below.

IMO this issue should be closed.

Let's say you have a structure like this and want to redact each of these:

```json
{
  "headers": {
    "token": "foo",
    "Authorization": "Bearer: jwt.is.here"
    "X_FOO_API_KEY": "0Spz6bOOxwfZOB3mM8r2"
  }
}
```

To achieve this, pass these three paths to fast-redact:

```javascript
paths: [...
  'headers.token',
  'headers.Authorization',
  'headers[`X-FOO-API-KEY`]'],
 }

Note that the last one uses the backtick character to enclose the `X-FOO-API-KEY`. Other quotes probably work, but I like the simplicity of avoiding escaping the single quote.

Alternatively, let's say you have each header accidentally in YAML like this and don't realize that it's 3 separate objects each in an array (I would _never_ do this, um, ever, but just in case anyone else would...):

```yaml
  # this is bad design - an array of objects - but for demo purposes...
  headers:
  - token: "foo"
  - Authorization: "jwt.is.here"
  - X-FOO-API-KEY: "0Spz6bOOxwfZOB3mM8r2"
  - ```

in this case, to redactthe last one I used this:

```javascript
paths = [
  ...
  'headers[*][`X-FOO-API-KEY`]',
```
