### ISSUE TITLE
redaction is not working for wild cards after level 2

### ISSUE THREAD

**Issue by gurjotkaur20** [davidmarkclements/fast-redact#57]
Issue: redaction is working upto level 2 when we use wildcards like *.*.* but after level 2, it is not working.

Here is the code where I want to redact field at level 3:
`const fastRedact = require('fast-redact')
const redact = fastRedact({
        paths: [
            '*.*.entityPanNumber',
            '*.*.*.entityPanNumber'        ],
        censor: '*****'
})

console.log(redact({ "1": { "2": { "entityPanNumber": "DEF" } } }))
console.log(redact({ "1": { "2": { "3": { "entityPanNumber": "DEF" } } }}))`

The output is:
`{"1":{"2":{"entityPanNumber":"*****"}}}
{"1":{"2":{"3":{"entityPanNumber":"DEF"}}}}`

**Comment by armandoborge** [comment]
The double dot (..entityPanNumber) notation is invalid (at least in ^3.1.1)
Trying your code results in error:

```
Error: pino – redact paths array contains an invalid path (..entityPanNumber)
```

As far as I know deep nesting redaction using the wildcard is not supported:
- https://github.com/davidmarkclements/fast-redact/issues/5
- https://github.com/davidmarkclements/fast-redact/issues/65
