### ISSUE TITLE
`rx` needs comments

### ISSUE THREAD

**Issue by jsumners** [davidmarkclements/fast-redact#7]
https://github.com/davidmarkclements/fast-redact/blob/3bc8dbe3547542b22b44262067d7390d5efc37b8/lib/rx.js#L3

That needs to be thoroughly commented. My eyes cross and I black out for some indeterminate time when I see it.

**Comment by davidmarkclements** [comment]
🤣 fair point - one way would be to run it through a regex explainer first and then add comments re the purpose of each part

**Comment by jsumners** [comment]
I have never thought to look for a regex explainer. Didn't realize they are a thing. Here's the output from https://regexper.com/#%2F%5B%5E.%5B%5C%5D%5D%2B%7C%5C%5B%28%3F%3A%28-%3F%5Cd%2B%28%3F%3A%5C.%5Cd%2B%29%3F%29%28%28%3F%3A%28%3F!%5C2%29%5B%5E%5C%5C%5D%7C%5C%5C.%29*%3F%29%5C2%29%5C%5D%7C%28%3F%3D%28%5C.%7C%5C%5B%5C%5D%29%28%3F%3A%5C4%7C%24%29%29%24%2F

![image](https://user-images.githubusercontent.com/321201/46573084-0868e100-c95e-11e8-968a-c99e772b79d3.png)

**Comment by mcollina** [comment]
Wow! That's amazing. How about we include it in the repo?

**Comment by jsumners** [comment]
I suppose it helps if there is some explanation along with it.
